# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\2019秋季学期（三上）\2019秋计算机网络及应用\HW1 big\Main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LogoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.LogoutButton.setText("")
        self.LogoutButton.setObjectName("LogoutButton")
        self.gridLayout.addWidget(self.LogoutButton, 0, 1, 1, 1)
        self.Account = QtWidgets.QLabel(self.centralwidget)
        self.Account.setObjectName("Account")
        self.gridLayout.addWidget(self.Account, 0, 0, 1, 1)
        self.FindFriendButton = QtWidgets.QPushButton(self.centralwidget)
        self.FindFriendButton.setObjectName("FindFriendButton")
        self.gridLayout.addWidget(self.FindFriendButton, 1, 1, 1, 1)
        self.FindFriendBox = QtWidgets.QLineEdit(self.centralwidget)
        self.FindFriendBox.setObjectName("FindFriendBox")
        self.gridLayout.addWidget(self.FindFriendBox, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.FriendListView = QtWidgets.QListView(self.centralwidget)
        self.FriendListView.setObjectName("FriendListView")
        self.verticalLayout.addWidget(self.FriendListView)
        self.FriendRequestButton = QtWidgets.QPushButton(self.centralwidget)
        self.FriendRequestButton.setText("")
        self.FriendRequestButton.setObjectName("FriendRequestButton")
        self.verticalLayout.addWidget(self.FriendRequestButton)
        self.GroupChatButton = QtWidgets.QPushButton(self.centralwidget)
        self.GroupChatButton.setText("")
        self.GroupChatButton.setObjectName("GroupChatButton")
        self.verticalLayout.addWidget(self.GroupChatButton)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ChatLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ChatLabel.setFont(font)
        self.ChatLabel.setText("")
        self.ChatLabel.setObjectName("ChatLabel")
        self.verticalLayout_2.addWidget(self.ChatLabel)
        self.MsgShowBox = QtWidgets.QTextEdit(self.centralwidget)
        self.MsgShowBox.setEnabled(True)
        self.MsgShowBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.MsgShowBox.setObjectName("MsgShowBox")
        self.verticalLayout_2.addWidget(self.MsgShowBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SendFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendFileButton.setText("")
        self.SendFileButton.setObjectName("SendFileButton")
        self.horizontalLayout_2.addWidget(self.SendFileButton)
        self.VoiceButton = QtWidgets.QPushButton(self.centralwidget)
        self.VoiceButton.setText("")
        self.VoiceButton.setObjectName("VoiceButton")
        self.horizontalLayout_2.addWidget(self.VoiceButton)
        self.VideoButton = QtWidgets.QPushButton(self.centralwidget)
        self.VideoButton.setText("")
        self.VideoButton.setObjectName("VideoButton")
        self.horizontalLayout_2.addWidget(self.VideoButton)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.SendMsgButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendMsgButton.setText("")
        self.SendMsgButton.setObjectName("SendMsgButton")
        self.horizontalLayout_2.addWidget(self.SendMsgButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.MsgInputBox = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MsgInputBox.sizePolicy().hasHeightForWidth())
        self.MsgInputBox.setSizePolicy(sizePolicy)
        self.MsgInputBox.setObjectName("MsgInputBox")
        self.verticalLayout_2.addWidget(self.MsgInputBox)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.properties = QtWidgets.QAction(MainWindow)
        self.properties.setObjectName("properties")
        self.menu.addAction(self.properties)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Account.setText(_translate("MainWindow", "当前账号："))
        self.FindFriendButton.setText(_translate("MainWindow", "查询好友"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.properties.setText(_translate("MainWindow", "设置"))

